"use client";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { Button, ErrorAlert, Field, Input, Unsupported } from "@/components/ui";
import { dohaApi } from "@/services/doha-api";
import { ApiError } from "@/services/api-client";
import type { VoiceProfileDto } from "@/types/api";
import { useStudioStore } from "@/stores/studio-store";
export function VoiceProfilePanel(){const [name,setName]=useState("");const [path,setPath]=useState("");const [consent,setConsent]=useState(false);const [profile,setProfile]=useState<VoiceProfileDto>();const store=useStudioStore();const create=useMutation({mutationFn:()=>dohaApi.createVoiceProfile({name,reference_file_path:path,consent_confirmed:true}),onSuccess:(value)=>{setProfile(value);store.patch({voiceProfileId:value.id})}});const remove=useMutation({mutationFn:()=>dohaApi.deleteVoiceProfile(profile!.id),onSuccess:()=>{setProfile(undefined);store.patch({voiceProfileId:""})}});const error=create.error||remove.error;return <section className="page-stack"><header className="page-heading"><p className="eyebrow">VOICE PROFILE</p><h1>동의된 목소리만, 안전하게</h1><p>현재 Backend 계약은 서버에 이미 존재하는 참조 파일 경로로 Profile을 생성합니다.</p></header><div className="two-panel"><form className="surface-card" onSubmit={(e)=>{e.preventDefault();create.mutate()}}><h2>Profile 생성</h2><Field label="Profile 이름" htmlFor="voice-name"><Input id="voice-name" value={name} onChange={(e)=>setName(e.target.value)} required /></Field><Field label="서버 참조 파일 경로" htmlFor="voice-path" hint="브라우저 업로드가 아니며 Backend가 접근 가능한 경로입니다."><Input id="voice-path" value={path} onChange={(e)=>setPath(e.target.value)} required /></Field><label className="check"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} />본인 음성 또는 명시적 동의를 받은 음성임을 확인합니다.</label>{error&&<ErrorAlert message={error instanceof ApiError?error.message:"요청에 실패했습니다."}/>}<Button disabled={!name||!path||!consent||create.isPending}>Profile 생성</Button><Unsupported>음성 파일 업로드</Unsupported></form><article className="surface-card"><h2>현재 Session Profile</h2>{profile?<div className="profile-card"><div className="avatar-wave">∿</div><div><strong>{profile.name}</strong><p>{profile.id}</p><small>동의 확인됨 · 이 세션에서 생성</small></div><Button className="danger" disabled={remove.isPending} onClick={()=>remove.mutate()}>삭제</Button></div>:<div className="empty"><span>◉</span><p>목록 API가 없어 가짜 Profile을 표시하지 않습니다.</p></div>}<hr/><Field label="기존 Profile UUID" htmlFor="existing-profile"><Input id="existing-profile" value={store.voiceProfileId} onChange={(e)=>store.patch({voiceProfileId:e.target.value})} /></Field></article></div></section>}
