"""Workspace REST API v1 transport Schema."""

from backend.schemas.workspace.bootstrap import WorkspaceBootstrapResult
from backend.schemas.workspace.common import (
    CollectionLinks,
    CollectionResponse,
    ErrorDetail,
    ErrorEnvelope,
    ErrorResponse,
    Pagination,
    SuccessResponse,
)
from backend.schemas.workspace.resources import (
    ArtifactDetail,
    AssetCreateRequest,
    AssetDetail,
    AssetSummary,
    AssetUpdateRequest,
    AssetVersionCreateRequest,
    AssetVersionDetail,
    AssetVersionSummary,
    CompositionSnapshotCreateRequest,
    CompositionSnapshotDetail,
    CompositionSnapshotSummary,
    ProjectAssetCreateRequest,
    ProjectAssetSummary,
    ProjectCreateRequest,
    ProjectDetail,
    ProjectSummary,
    ProjectUpdateRequest,
    SnapshotItemCreateRequest,
    SnapshotItemDetail,
    WorkspaceDetail,
    WorkspaceSummary,
    WorkspaceUpdateRequest,
)

__all__ = [
    "ArtifactDetail",
    "AssetCreateRequest",
    "AssetDetail",
    "AssetSummary",
    "AssetUpdateRequest",
    "AssetVersionCreateRequest",
    "AssetVersionDetail",
    "AssetVersionSummary",
    "CollectionLinks",
    "CollectionResponse",
    "CompositionSnapshotCreateRequest",
    "CompositionSnapshotDetail",
    "CompositionSnapshotSummary",
    "ErrorDetail",
    "ErrorEnvelope",
    "ErrorResponse",
    "Pagination",
    "ProjectAssetCreateRequest",
    "ProjectAssetSummary",
    "ProjectCreateRequest",
    "ProjectDetail",
    "ProjectSummary",
    "ProjectUpdateRequest",
    "SuccessResponse",
    "SnapshotItemCreateRequest",
    "SnapshotItemDetail",
    "WorkspaceBootstrapResult",
    "WorkspaceDetail",
    "WorkspaceSummary",
    "WorkspaceUpdateRequest",
]
