"""DohaVocal consumer contract foundation."""

from .client import VocalProviderClient
from .contracts import (
    DOHAVOCAL_CONTRACT_VERSION,
    DOHAVOCAL_OPERATIONS,
    DOHAVOCAL_PROVIDER_ID,
    AnyVocalJob,
    BaseVocalJob,
    VocalAnalysisInput,
    VocalAnalysisType,
    VocalArtifactLineage,
    VocalCapabilities,
    VocalCapability,
    VocalCorrectionInput,
    VocalCorrectionType,
    VocalCreateJobRequest,
    VocalGenerationInput,
    VocalHealthProbe,
    VocalJobStatus,
    VocalModelManifest,
    VocalProviderResultCandidate,
    VocalReadinessProbe,
    VoiceConversionInput,
)
from .errors import (
    VocalProviderApplicationError,
    VocalProviderConsumerError,
    VocalProviderContractVersionError,
    VocalProviderErrorDetail,
    VocalProviderInvalidResponseError,
    VocalProviderTimeoutError,
    VocalProviderTransportError,
)
from .http_transport import HttpVocalProviderTransport
from .mapping import AuthorizedVocalJobContext, map_authorized_create_job
from .transport import (
    VocalProviderTransport,
    VocalTransportRequest,
    VocalTransportResponse,
)

__all__ = [
    "DOHAVOCAL_CONTRACT_VERSION",
    "DOHAVOCAL_OPERATIONS",
    "DOHAVOCAL_PROVIDER_ID",
    "AnyVocalJob",
    "AuthorizedVocalJobContext",
    "BaseVocalJob",
    "HttpVocalProviderTransport",
    "VocalAnalysisInput",
    "VocalAnalysisType",
    "VocalArtifactLineage",
    "VocalCapabilities",
    "VocalCapability",
    "VocalCorrectionInput",
    "VocalCorrectionType",
    "VocalCreateJobRequest",
    "VocalGenerationInput",
    "VocalHealthProbe",
    "VocalJobStatus",
    "VocalModelManifest",
    "VocalProviderApplicationError",
    "VocalProviderClient",
    "VocalProviderConsumerError",
    "VocalProviderContractVersionError",
    "VocalProviderErrorDetail",
    "VocalProviderInvalidResponseError",
    "VocalProviderResultCandidate",
    "VocalReadinessProbe",
    "VocalProviderTimeoutError",
    "VocalProviderTransport",
    "VocalProviderTransportError",
    "VocalTransportRequest",
    "VocalTransportResponse",
    "VoiceConversionInput",
    "map_authorized_create_job",
]
